model_name: ortho_lines_ortho_lines.pth
original_url: https://huggingface.co/yzamir/ortho-lines/resolve/main/ortho_lines.pth
file_extension: pth
split_size_mb: 95
total_size_bytes: 749400872
parts_count: 8
created_at: 2025-11-20T12:24:37Z
sha256: 60f16d00e6a8be1a7ebcbe5deac8ac7579c6fdfa0e94a55ea5097f6e70c17250
